version: '3.7'
services:
  app:
    build:
      args:
        user: nobody
        work_dir: /var/www/admin
        config_dir: /config
        script_dir: /script
        src_dir: /src
      context: .
      dockerfile: Dockerfile
    container_name: unilabot-app
    restart: unless-stopped
    working_dir: /var/www/admin
    networks:
      - local

networks:
  local:
    driver: bridge
