version: '3.7'

networks:
  local:
    driver: bridge 

volumes:
  logdata:

services:
  app:
    image: ${IMAGE_PROD}:latest
    container_name: unilabot
    working_dir: ${WORK_DIR}
    restart: on-failure
    volumes:
      - logdata:${VOLUMES}
    networks:
      - local